import { createContext, useContext, useEffect, useState } from "react";

const InvoicesContext = createContext(null);

export function InvoicesProvider({ children }) {

    const titles = [
        'Registration Form - N15,000.00',
        'Speech & Prize - N5,000.00',
        'Secondary School Fee - N80,000.00',
        'Primary School Fee - N70,000.00',
        'Nursery School Fee - N55,000.00',
        'Exam - N2,500.00',
        'PTA - N1,000.00',
    ]
    const [invoices, setInvoices] = useState(localStorage.getItem('invoices') ? JSON.parse(localStorage.getItem('invoices')) : [
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: 78282989438934,
            id: 'IN839833',
            student: 'Aisha Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Jss 3',
            paymentMethod: 'Cash',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '5,000.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Unpaid',
            status2: 'Active',
            date: '2026-02-15'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN392003',
            student: 'Aisha Yusuf Karamba',
            regno: 'NSC-26-0002',
            class: 'SS 3',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '93,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN982832',
            student: 'Aisha Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Jss 3',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN927323',
            student: 'Adama Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Primary 4',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN333333',
            student: 'Maimuna Ahmodu',
            regno: 'NSC-26-0004',
            class: 'Primary 2',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN029392',
            student: 'Maryam Abdulkadir',
            regno: 'NSC-26-0005',
            class: 'SS 3',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'School Fee',
            total: '93,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN930283',
            student: 'Aisha Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Jss 3',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '5,000.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Unpaid',
            status2: 'Active',
            date: '2026-02-15'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN028493',
            student: 'Aisha Yusuf Karamba',
            regno: 'NSC-26-0002',
            class: 'SS 3',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '93,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN399339',
            student: 'Aisha Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Jss 3',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN0303033',
            student: 'Adama Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Primary 4',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN333689',
            student: 'Maimuna Ahmodu',
            regno: 'NSC-26-0004',
            class: 'Primary 2',
            paymentMethod: 'Cash',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN930923',
            student: 'Maryam Abdulkadir',
            regno: 'NSC-26-0005',
            class: 'SS 3',
            paymentMethod: 'Cash',
            account: 'Jaiz Bank - 0000000001',
            category: 'School Fee',
            total: '93,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN028392',
            student: 'Aisha Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Jss 3',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '5,000.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Unpaid',
            status2: 'Active',
            date: '2026-02-15'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN8393782',
            student: 'Aisha Yusuf Karamba',
            regno: 'NSC-26-0002',
            class: 'SS 3',
            paymentMethod: 'Cash',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '93,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN829023',
            student: 'Aisha Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Jss 3',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN743795',
            student: 'Adama Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Primary 4',
            paymentMethod: 'Cash',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN929404',
            student: 'Maimuna Ahmodu',
            regno: 'NSC-26-0004',
            class: 'Primary 2',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN893055',
            student: 'Maryam Abdulkadir',
            regno: 'NSC-26-0005',
            class: 'SS 3',
            paymentMethod: 'Cash',
            account: 'Jaiz Bank - 0000000001',
            category: 'School Fee',
            total: '93,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN090903',
            student: 'Aisha Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Jss 3',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '5,000.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Unpaid',
            status2: 'Active',
            date: '2026-02-15'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN363636',
            student: 'Aisha Yusuf Karamba',
            regno: 'NSC-26-0002',
            class: 'SS 3',
            paymentMethod: 'Cash',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '93,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN878756',
            student: 'Aisha Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Jss 3',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN098765',
            student: 'Adama Ahmodu',
            regno: 'NSC-26-0002',
            class: 'Primary 4',
            paymentMethod: 'Cash',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN838333',
            student: 'Maimuna Ahmodu',
            regno: 'NSC-26-0004',
            class: 'Primary 2',
            paymentMethod: 'Transfer',
            account: 'Jaiz Bank - 0000000001',
            category: 'Registration',
            total: '98,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
        {
            title: titles[Math.floor(Math.random() * titles.length) + 1],
            quantity: Math.floor(Math.random() * 8) + 1,
            uniqueId: crypto.randomUUID(),
            id: 'IN121212',
            student: 'Maryam Abdulkadir',
            regno: 'NSC-26-0005',
            class: 'SS 3',
            paymentMethod: 'Cash',
            account: 'Jaiz Bank - 0000000001',
            category: 'School Fee',
            total: '93,500.00',
            session: '2025/2026',
            term: 'Second term',
            status1: 'Paid',
            status2: 'Successful',
            date: '2026-01-28'
        },
    ]);

    const [registration, setRegistration] = useState(localStorage.getItem('registration') ? JSON.parse(localStorage.getItem('registration')) : [
        {
            id: 1,
            title: 'REGISTRATION FORM',
            amount: '15,000.00'
        },
        {
            id: 2,
            title: 'Speech & Prize',
            amount: '5,000.00'
        },
        {
            id: 3,
            title: 'Secondary School Fee',
            amount: '80,000.00'
        },
        {
            id: 4,
            title: 'Primary School Fee',
            amount: '70,000.00'
        },
        {
            id: 5,
            title: 'Exam',
            amount: '2,500.00'
        },
        {
            id: 6,
            title: 'PTA',
            amount: '1,000.00'
        },
        {
            id: 7,
            title: 'Nursery School Fee',
            amount: '55,000.00'
        }
    ]);

    useEffect(() => {
        localStorage.setItem('invoices', JSON.stringify(invoices));
    }, [invoices]);

    useEffect(() => {
        localStorage.setItem('registration', JSON.stringify(registration));
    }, [registration]);

    return (
        <InvoicesContext.Provider value={{ invoices, setInvoices, registration, setRegistration }}>{children}</InvoicesContext.Provider>
    )
}

export function useInvoices() {
    return useContext(InvoicesContext);
}