import { createContext, useContext, useEffect, useState } from "react";

const PayslipsContext = createContext(null);

export function PayslipsProvider({ children }) {

    const [payslips, setPayslips] = useState(localStorage.getItem('payslips') ? JSON.parse(localStorage.getItem('payslips')) : [
        {
            id: 1,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 2,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 3,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 4,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 5,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 6,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 7,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 8,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 9,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 10,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 11,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 12,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 13,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 14,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 15,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 16,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 17,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 18,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 19,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 20,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 21,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 22,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 23,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 24,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 25,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 26,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 27,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 28,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 29,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 30,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 31,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 32,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 33,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 34,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 35,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 36,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 37,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 38,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 39,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 40,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 41,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 42,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 43,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 44,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 45,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 46,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 47,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 48,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 49,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
        {
            id: 50,
            staff: 'Aisha Ahmed Aminu',
            period: '2020-01',
            salary: 13000,
            status: 'Approved',
            date: '2026-02-04',
        },
    ]);

    useEffect(() => {
        localStorage.setItem('payslips', JSON.stringify(payslips));
    }, [payslips]);

    return (
        <PayslipsContext.Provider value={{ payslips, setPayslips }}> {children}</PayslipsContext.Provider >
    )
}

export function usePayslips() {
    return useContext(PayslipsContext);
}