import { createContext, useContext, useState } from "react";

const StaffsContext = createContext(null);

export function StaffsProvider({ children }) {
    const [staffsData, setStaffsData] = useState(localStorage.getItem('staffs') ? JSON.parse(localStorage.getItem('staffs')) : [
        {
            uniqueId: 'kskdau8742wdu24in2n442f',
            id: 'NSC-26-0001',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            department: 'Others',
            position: 'Other',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'jkauw329238kjs92e9kje',
            id: 'NSC-26-0002',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            department: 'Science',
            position: 'Teacher',
            category: 'Academic',
            type: 'Part-Time',
            status: 'Active',
        },
        {
            uniqueId: 'njkdwkjdw90w0932nm28924n',
            id: 'NSC-26-0003',
            fName: 'Maimuna',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'j98dds9832jkb29dw89dwdv',
            id: 'NSC-26-0004',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            department: 'Sanity',
            position: 'Nanny',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'iodwo09wjkdw9842nw9d8432',
            id: 'NSC-26-0005',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'kjsojdw0923jke2m9dwe2nndwk',
            id: 'NSC-26-0006',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            department: 'Art',
            position: 'Teacher',
            category: 'Academic',
            type: 'Part-Time',
            status: 'Active',
        },
        {
            uniqueId: 'kjdojew098842jwemdwkjfweifdmkr3',
            id: 'NSC-26-0007',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            department: 'Science',
            position: 'Teacher',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'kxoids8723jdwnmjkdwij432kjewds',
            id: 'NSC-26-0008',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            department: 'Art',
            position: 'Teacher',
            category: 'Academic',
            type: 'Part-Time',
            status: 'Active',
        },
        {
            uniqueId: 'jda9842hw9824nkkb42tijof43v3wd',
            id: 'NSC-26-0009',
            fName: 'Maimuna',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'jds9842bb9fu4b94220nvojnjkwsnmc',
            id: 'NSC-26-0010',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'oadoewh082f082942ndwkskkjdsoiwe098',
            id: 'NSC-26-0011',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'oasi89942b98ewjkkjwkj9824jkdw98wd',
            id: 'NSC-26-0012',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            department: 'Art',
            position: 'Teacher',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'oidwoewhjoewf89982kjrwjiwdb42ihjb',
            id: 'NSC-26-0013',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            department: 'Sanity',
            position: 'Nanny',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'oiuoew8924bnfjjkwuo42jkwrijqpcib2ef',
            id: 'NSC-26-0014',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            department: 'Art',
            position: 'Teacher',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'oihwq0824oefhnfewoi2428johrw9uo43',
            id: 'NSC-26-0015',
            fName: 'Maimuna',
            mName: '',
            lName: 'Ahmodu',
            department: 'Science',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'jwfi4324hjlk208urwjo4290qeiou42ny',
            id: 'NSC-26-0016',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'isniwjkdw83h845bf83fij03djdmdmdkd',
            id: 'NSC-26-0017',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'kjkjwduiew9874343nbfinjrrgj24jfkrj',
            id: 'NSC-26-0018',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            department: 'Art',
            position: 'Teacher',
            category: 'Academic',
            type: 'Part-Time',
            status: 'Active',
        },
        {
            uniqueId: 'sdoleoerlkngrelerjkejerkhjergs439n',
            id: 'NSC-26-0019',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            department: 'Others',
            position: 'Other',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'kjsdoro3h894nwfei943nojeoiuewr',
            id: 'NSC-26-0020',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            department: 'Art',
            position: 'Teacher',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'oidhf82wjefn4209jnrwnwjkbgfrkd',
            id: 'NSC-26-0021',
            fName: 'Maimuna',
            mName: '',
            lName: 'Ahmodu',
            department: 'Sanity',
            position: 'Nanny',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'oiuwdhf0842ewj942nfdvnrnuro3w4',
            id: 'NSC-26-0022',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'oiafojvds09842nuioeoejoi43jkrew',
            id: 'NSC-26-0023',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            department: 'Science',
            position: 'Teacher',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'oiwnff9843nb489bu84943jkrjkwoiw',
            id: 'NSC-26-0024',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            department: 'Art',
            position: 'Teacher',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'kjdkj984329842nwekjwkjwe94u93nkb',
            id: 'NSC-26-0025',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'jdkjwou3infw8943kjsjkwkjrjwrjwrkk',
            id: 'NSC-26-0026',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'oi249h432ngfr39gnr3rnvjwkrjgwjkrw',
            id: 'NSC-26-0027',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'kjbwout429tr42gr309jkfwgeijrkeoje',
            id: 'NSC-26-0028',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            department: 'Science',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'jwdfo38943jnwrjkwjgrwhgkrwlhwrlww',
            id: 'NSC-26-0029',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            department: 'Others',
            position: 'Other',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'iwoh4082h0423kjrjkksalcnnie84btbg',
            id: 'NSC-26-0030',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'jje8492ewq98wjnlwekwe843kjlwrlkwr',
            id: 'NSC-26-0031',
            fName: 'Maimuna',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Part-Time',
            status: 'Active',
        },
        {
            uniqueId: 'weiuiuwe24898uwjdkwkjwkjwkjwkjwekj',
            id: 'NSC-26-0032',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'lsoiudyt0rwh98339hr3rjjjoifaw98e2',
            id: 'NSC-26-0033',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            department: 'Art',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'kdnf0i0942nwrjwjoiu34wjwhojrwnvdo',
            id: 'NSC-26-0034',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            department: 'Sanity',
            position: 'Nanny',
            category: 'Non Academic',
            type: 'Part-Time',
            status: 'Active',
        },
        {
            uniqueId: 'jwgoiu4899843nfjrijwkjwl4j3ojn344',
            id: 'NSC-26-0035',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            department: 'Science',
            position: 'Teacher',
            category: 'Non Academic',
            type: 'Full-Time',
            status: 'Active',
        },
        {
            uniqueId: 'dauf09824nfe98h42jwreowewjoow89w',
            id: 'NSC-26-0036',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            department: 'Others',
            position: 'Other',
            category: 'Academic',
            type: 'Full-Time',
            status: 'Active',
        },
    ]);

    const activeStaffs = staffsData.filter((staffs) => staffs.status === 'Active');
    const academicStaffs = staffsData.filter((staffs) => staffs.category === 'Academic');
    const nonAcademicStaffs = staffsData.filter((staffs) => staffs.category === 'Non Academic');

    return (
        <StaffsContext.Provider value={{ staffsData, setStaffsData, activeStaffs, academicStaffs, nonAcademicStaffs }}>{children}</StaffsContext.Provider>
    )
}

export function useStaffs() {
    return useContext(StaffsContext);
}