import { createContext, useContext, useState } from "react";

const StudentContext = createContext(null);

export function StudentProvider({ children }) {
    const [studentsData, setStudentsData] = useState(localStorage.getItem('students') ? JSON.parse(localStorage.getItem('students')) : [
        {
            id: 1,
            regno: 'NSC-26-0006',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Male',
            dob: '2020-01-26',
            class: 'Nursery 1',
            status: 'active',
        },
        {
            id: 2,
            regno: 'NSC-26-0005',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            gender: 'Female',
            dob: '2009-11-27',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 3,
            regno: 'NSC-26-0004',
            fName: 'Maimuna',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2026-11-16',
            class: 'Primary 2',
            status: 'active',
        },
        {
            id: 4,
            regno: 'NSC-26-0003',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2024-08-08',
            class: 'Primary 4',
            status: 'active',
        },
        {
            id: 5,
            regno: 'NSC-26-0002',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2011-10-11',
            class: 'JSS 3',
            status: 'active',
        },
        {
            id: 6,
            regno: 'NSC-26-0001',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            gender: 'Female',
            dob: '2008-04-26',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 7,
            regno: 'NSC-26-0006',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Male',
            dob: '2020-01-26',
            class: 'Nursery 1',
            status: 'active',
        },
        {
            id: 8,
            regno: 'NSC-26-0005',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            gender: 'Female',
            dob: '2009-11-27',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 9,
            regno: 'NSC-26-0004',
            fName: 'Maimuna',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2026-11-16',
            class: 'Primary 2',
            status: 'active',
        },
        {
            id: 10,
            regno: 'NSC-26-0003',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2024-08-08',
            class: 'Primary 4',
            status: 'active',
        },
        {
            id: 11,
            regno: 'NSC-26-0002',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2011-10-11',
            class: 'JSS 3',
            status: 'active',
        },
        {
            id: 12,
            regno: 'NSC-26-0001',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            gender: 'Female',
            dob: '2008-04-26',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 13,
            regno: 'NSC-26-0006',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Male',
            dob: '2020-01-26',
            class: 'Nursery 1',
            status: 'active',
        },
        {
            id: 14,
            regno: 'NSC-26-0005',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            gender: 'Female',
            dob: '2009-11-27',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 15,
            regno: 'NSC-26-0004',
            fName: 'Maimuna',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2026-11-16',
            class: 'Primary 2',
            status: 'active',
        },
        {
            id: 16,
            regno: 'NSC-26-0003',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2024-08-08',
            class: 'Primary 4',
            status: 'active',
        },
        {
            id: 17,
            regno: 'NSC-26-0002',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2011-10-11',
            class: 'JSS 3',
            status: 'active',
        },
        {
            id: 18,
            regno: 'NSC-26-0001',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            gender: 'Female',
            dob: '2008-04-26',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 19,
            regno: 'NSC-26-0006',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Male',
            dob: '2020-01-26',
            class: 'Nursery 1',
            status: 'active',
        },
        {
            id: 20,
            regno: 'NSC-26-0005',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            gender: 'Female',
            dob: '2009-11-27',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 21,
            regno: 'NSC-26-0004',
            fName: 'Maimuna',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2026-11-16',
            class: 'Primary 2',
            status: 'active',
        },
        {
            id: 22,
            regno: 'NSC-26-0003',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2024-08-08',
            class: 'Primary 4',
            status: 'active',
        },
        {
            id: 23,
            regno: 'NSC-26-0002',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2011-10-11',
            class: 'JSS 3',
            status: 'active',
        },
        {
            id: 24,
            regno: 'NSC-26-0001',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            gender: 'Female',
            dob: '2008-04-26',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 25,
            regno: 'NSC-26-0006',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Male',
            dob: '2020-01-26',
            class: 'Nursery 1',
            status: 'active',
        },
        {
            id: 26,
            regno: 'NSC-26-0005',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            gender: 'Female',
            dob: '2009-11-27',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 27,
            regno: 'NSC-26-0003',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2024-08-08',
            class: 'Primary 4',
            status: 'active',
        },
        {
            id: 28,
            regno: 'NSC-26-0002',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2011-10-11',
            class: 'JSS 3',
            status: 'active',
        },
        {
            id: 29,
            regno: 'NSC-26-0001',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            gender: 'Female',
            dob: '2008-04-26',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 30,
            regno: 'NSC-26-0006',
            fName: 'Mohammed',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Male',
            dob: '2020-01-26',
            class: 'Nursery 1',
            status: 'active',
        },
        {
            id: 31,
            regno: 'NSC-26-0005',
            fName: 'Maryam',
            mName: 'Abdulkadir',
            lName: 'Ibrahim',
            gender: 'Female',
            dob: '2009-11-27',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 32,
            regno: 'NSC-26-0004',
            fName: 'Maimuna',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2026-11-16',
            class: 'Primary 2',
            status: 'active',
        },
        {
            id: 33,
            regno: 'NSC-26-0003',
            fName: 'Adama',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2024-08-08',
            class: 'Primary 4',
            status: 'active',
        },
        {
            id: 34,
            regno: 'NSC-26-0002',
            fName: 'Aisha',
            mName: '',
            lName: 'Ahmodu',
            gender: 'Female',
            dob: '2011-10-11',
            class: 'JSS 3',
            status: 'active',
        },
        {
            id: 35,
            regno: 'NSC-26-0001',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            gender: 'Female',
            dob: '2008-04-26',
            class: 'SS 3',
            status: 'active',
        },
        {
            id: 36,
            regno: 'NSC-26-0001',
            fName: 'Aisha',
            mName: 'Yusuf',
            lName: 'Karamba',
            gender: 'Female',
            dob: '2008-04-26',
            class: 'SS 3',
            status: 'active',
        },
    ]);

    const [currentStudent, setCurrentStudent] = useState({id: '', fName: '', mName: '', lName: '', regno: '', dob: '', gender: '', status: '', state: '', lga: '', address: '', gName: '', relation: '', pNo: '', wNo: '', email: '', gAddress: ''});

    return (
        <StudentContext.Provider value={{ studentsData, setStudentsData, currentStudent, setCurrentStudent }}>{children}</StudentContext.Provider>
    )
}

export function useStudent() {
    return useContext(StudentContext);
}